Repository mseninc/blog, pull requests merged in 2024-05, with the labels that each got.

#314 author.yaml に active を追加, new.sh で active なメンバーのみ表示されるように修正
  author.yaml
  new.sh
Labels: Automation

#316 iDeCo をやめて企業型 DC に移換する手順
  Ryotaro49/2023/ideco-to-dc-conversion-guide/images/DC_iDeCo.png
  Ryotaro49/2023/ideco-to-dc-conversion-guide/images/HERO.png
  Ryotaro49/2023/ideco-to-dc-conversion-guide/images/kanyusya_unyousasizusya.png
  Ryotaro49/2023/ideco-to-dc-conversion-guide/images/sousitsu_riyu.png
  Ryotaro49/2023/ideco-to-dc-conversion-guide/index.md
Labels: Post, textlint, release

#323 [Facebook post workflow] Rename workflow file name
  .github/workflows/post-to-facebook.yml
Labels: 改善

#321 [Google Forms] フォーム送信時に「回答を編集」リンクを含んだ通知メールを管理者に送信する
  .github/prh/rules/WEB+DB_PRESS_modified.yml
  .textlintrc
  kenzauros/2024/google-forms-notify-response-with-edit-url/images/HERO.png
  kenzauros/2024/google-forms-notify-response-with-edit-url/images/available-triggers.png
  kenzauros/2024/google-forms-notify-response-with-edit-url/images/edit-response1.png
  kenzauros/2024/google-forms-notify-response-with-edit-url/images/edit-response2.png
  kenzauros/2024/google-forms-notify-response-with-edit-url/images/gas-class-reference-ja-en.png
  kenzauros/2024/google-forms-notify-response-with-edit-url/images/notification-mail.png
  kenzauros/2024/google-forms-notify-response-with-edit-url/images/trigger-settings.png
  kenzauros/2024/google-forms-notify-response-with-edit-url/index.md
Labels: Post, textlint, release

#322 2023年度の事業継続計画訓練（あべの防災センター）を実施しました
  jinna-i/2024/business-continuity-planning-training-in-2023/images/001.png
  jinna-i/2024/business-continuity-planning-training-in-2023/images/002.jpg
  jinna-i/2024/business-continuity-planning-training-in-2023/images/003.jpg
  jinna-i/2024/business-continuity-planning-training-in-2023/images/004.jpg
  jinna-i/2024/business-continuity-planning-training-in-2023/images/005.jpg
  jinna-i/2024/business-continuity-planning-training-in-2023/images/006.jpg
  jinna-i/2024/business-continuity-planning-training-in-2023/images/007.jpg
  jinna-i/2024/business-continuity-planning-training-in-2023/images/HERO.png
  jinna-i/2024/business-continuity-planning-training-in-2023/index.md
Labels: Post, textlint, release
