Repository mseninc/blog, pull requests merged in 2024-06, with the labels that each got.

#324 AWS Polly を使ってテキストを音声に変換してアプリ上で再生する方法
  junya-gera/2024/convert-text-to-speech-aws-polly-web-speech-api/images/1.png
  junya-gera/2024/convert-text-to-speech-aws-polly-web-speech-api/images/HERO.png
  junya-gera/2024/convert-text-to-speech-aws-polly-web-speech-api/index.md
Labels: Post, textlint, release

#325 [第2弾] Zabbix から ESET Server Security for Linux のウイルス検出を監視する
  jinna-i/2024/monitor-eset-virus-detection-from-zabbix-vol2/images/001.png
  jinna-i/2024/monitor-eset-virus-detection-from-zabbix-vol2/images/002.png
  jinna-i/2024/monitor-eset-virus-detection-from-zabbix-vol2/images/003.png
  jinna-i/2024/monitor-eset-virus-detection-from-zabbix-vol2/images/HERO.png
  jinna-i/2024/monitor-eset-virus-detection-from-zabbix-vol2/index.md
Labels: Post, textlint, release

#326 「このワークステーションとプライマリ ドメインとの信頼関係に失敗しました」の解決方法
  jinna-i/2024/restore-trust-between-the-workstation-and-the-primary-domain/images/001.png
  jinna-i/2024/restore-trust-between-the-workstation-and-the-primary-domain/images/002.png
  jinna-i/2024/restore-trust-between-the-workstation-and-the-primary-domain/images/003.png
  jinna-i/2024/restore-trust-between-the-workstation-and-the-primary-domain/images/004.png
  jinna-i/2024/restore-trust-between-the-workstation-and-the-primary-domain/images/005.png
  jinna-i/2024/restore-trust-between-the-workstation-and-the-primary-domain/images/HERO.png
  jinna-i/2024/restore-trust-between-the-workstation-and-the-primary-domain/index.md
Labels: Post, release

#329 自己紹介文を更新
  author.yaml
Labels: 修正
